import type { Category, Phrase } from "@/types";

type SeedCategory = Omit<Category, "createdAt">;
type SeedPhrase = Omit<Phrase, "createdAt">;

export const seedCategories: SeedCategory[] = [
  {
    id: "essentials",
    name: "Essentials",
    emoji: "⭐",
    color: "#3F6E8C",
    sortOrder: 0,
    isDefault: true
  },
  {
    id: "restaurant",
    name: "Restaurant",
    emoji: "🍽️",
    color: "#B08443",
    sortOrder: 1,
    isDefault: true
  },
  {
    id: "shopping",
    name: "Shopping",
    emoji: "🛍️",
    color: "#5C7A5A",
    sortOrder: 2,
    isDefault: true
  },
  {
    id: "medical",
    name: "Medical",
    emoji: "⚕️",
    color: "#B05B4D",
    sortOrder: 3,
    isDefault: true
  },
  {
    id: "transportation",
    name: "Transportation",
    emoji: "🚌",
    color: "#7A6485",
    sortOrder: 4,
    isDefault: true
  },
  {
    id: "social",
    name: "Social",
    emoji: "💬",
    color: "#2F7E6B",
    sortOrder: 5,
    isDefault: true
  }
];

export const seedPhrases: SeedPhrase[] = [
  {
    id: "phrase-yes",
    text: "Yes.",
    label: "Yes",
    emoji: "✅",
    color: "#5C7A5A",
    categoryId: "essentials",
    voiceId: null,
    language: null,
    isPinned: true,
    isQuickAccess: true,
    sortOrder: 0,
    isDefault: true
  },
  {
    id: "phrase-no",
    text: "No.",
    label: "No",
    emoji: "❌",
    color: "#B05B4D",
    categoryId: "essentials",
    voiceId: null,
    language: null,
    isPinned: true,
    isQuickAccess: true,
    sortOrder: 1,
    isDefault: true
  },
  {
    id: "phrase-thank-you",
    text: "Thank you.",
    label: "Thank you",
    emoji: "🙏",
    color: "#3F6E8C",
    categoryId: "essentials",
    voiceId: null,
    language: null,
    isPinned: true,
    isQuickAccess: true,
    sortOrder: 2,
    isDefault: true
  },
  {
    id: "phrase-please",
    text: "Please.",
    label: "Please",
    emoji: "🤲",
    color: "#2F7E6B",
    categoryId: "essentials",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 3,
    isDefault: true
  },
  {
    id: "phrase-help",
    text: "I need help.",
    label: "Help",
    emoji: "🆘",
    color: "#B05B4D",
    categoryId: "essentials",
    voiceId: null,
    language: null,
    isPinned: true,
    isQuickAccess: true,
    sortOrder: 4,
    isDefault: true
  },
  {
    id: "phrase-excuse-me",
    text: "Excuse me.",
    label: "Excuse me",
    emoji: "👋",
    color: "#B08443",
    categoryId: "essentials",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 5,
    isDefault: true
  },
  {
    id: "phrase-dont-understand",
    text: "I don't understand.",
    label: "I don't understand",
    emoji: "❓",
    color: "#7A6485",
    categoryId: "essentials",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 6,
    isDefault: true
  },
  {
    id: "phrase-repeat",
    text: "Can you repeat that?",
    label: "Repeat",
    emoji: "🔁",
    color: "#7C776C",
    categoryId: "essentials",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 7,
    isDefault: true
  },
  {
    id: "phrase-order",
    text: "I'd like to order.",
    label: "Order",
    emoji: "🍽️",
    color: "#B08443",
    categoryId: "restaurant",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 0,
    isDefault: true
  },
  {
    id: "phrase-menu",
    text: "Can I see the menu?",
    label: "Menu",
    emoji: "📋",
    color: "#B08443",
    categoryId: "restaurant",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 1,
    isDefault: true
  },
  {
    id: "phrase-water",
    text: "Water, please.",
    label: "Water",
    emoji: "💧",
    color: "#3F6E8C",
    categoryId: "restaurant",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 2,
    isDefault: true
  },
  {
    id: "phrase-check",
    text: "The check, please.",
    label: "Check",
    emoji: "🧾",
    color: "#7C776C",
    categoryId: "restaurant",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 3,
    isDefault: true
  },
  {
    id: "phrase-allergy",
    text: "I have a food allergy.",
    label: "Food allergy",
    emoji: "⚠️",
    color: "#B05B4D",
    categoryId: "restaurant",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 4,
    isDefault: true
  },
  {
    id: "phrase-no-dairy",
    text: "No dairy, gluten, or nuts, please.",
    label: "No allergens",
    emoji: "🥜",
    color: "#B05B4D",
    categoryId: "restaurant",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 5,
    isDefault: true
  },
  {
    id: "phrase-to-go",
    text: "Can I get this to go?",
    label: "To go",
    emoji: "🥡",
    color: "#5C7A5A",
    categoryId: "restaurant",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 6,
    isDefault: true
  },
  {
    id: "phrase-cost",
    text: "How much does this cost?",
    label: "Cost",
    emoji: "💵",
    color: "#5C7A5A",
    categoryId: "shopping",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 0,
    isDefault: true
  },
  {
    id: "phrase-size",
    text: "Do you have this in a different size?",
    label: "Different size",
    emoji: "📏",
    color: "#7A6485",
    categoryId: "shopping",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 1,
    isDefault: true
  },
  {
    id: "phrase-aisle",
    text: "Where is this aisle or section?",
    label: "Where is it?",
    emoji: "🧭",
    color: "#3F6E8C",
    categoryId: "shopping",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 2,
    isDefault: true
  },
  {
    id: "phrase-looking",
    text: "I'm just looking, thank you.",
    label: "Just looking",
    emoji: "👀",
    color: "#7C776C",
    categoryId: "shopping",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 3,
    isDefault: true
  },
  {
    id: "phrase-card",
    text: "Can I pay with card?",
    label: "Pay with card",
    emoji: "💳",
    color: "#5C7A5A",
    categoryId: "shopping",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 4,
    isDefault: true
  },
  {
    id: "phrase-pain",
    text: "I'm in pain.",
    label: "Pain",
    emoji: "⚕️",
    color: "#B05B4D",
    categoryId: "medical",
    voiceId: null,
    language: null,
    isPinned: true,
    isQuickAccess: false,
    sortOrder: 0,
    isDefault: true
  },
  {
    id: "phrase-medication",
    text: "I need my medication.",
    label: "Medication",
    emoji: "💊",
    color: "#B05B4D",
    categoryId: "medical",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 1,
    isDefault: true
  },
  {
    id: "phrase-allergic-x",
    text: "I'm allergic to this.",
    label: "Allergic",
    emoji: "⚠️",
    color: "#B05B4D",
    categoryId: "medical",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 2,
    isDefault: true
  },
  {
    id: "phrase-doctor",
    text: "I need to see a doctor.",
    label: "Doctor",
    emoji: "🩺",
    color: "#3F6E8C",
    categoryId: "medical",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 3,
    isDefault: true
  },
  {
    id: "phrase-med-info",
    text: "Here is my medical information.",
    label: "Medical info",
    emoji: "🪪",
    color: "#7C776C",
    categoryId: "medical",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 4,
    isDefault: true
  },
  {
    id: "phrase-dizzy",
    text: "I feel dizzy or nauseous.",
    label: "Dizzy",
    emoji: "😵",
    color: "#B08443",
    categoryId: "medical",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 5,
    isDefault: true
  },
  {
    id: "phrase-destination",
    text: "I need to go to this destination.",
    label: "Destination",
    emoji: "📍",
    color: "#7A6485",
    categoryId: "transportation",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 0,
    isDefault: true
  },
  {
    id: "phrase-fare",
    text: "How much is the fare?",
    label: "Fare",
    emoji: "🎫",
    color: "#5C7A5A",
    categoryId: "transportation",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 1,
    isDefault: true
  },
  {
    id: "phrase-stop-here",
    text: "Please stop here.",
    label: "Stop here",
    emoji: "🛑",
    color: "#B05B4D",
    categoryId: "transportation",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 2,
    isDefault: true
  },
  {
    id: "phrase-accessible",
    text: "I need an accessible entrance.",
    label: "Accessible entrance",
    emoji: "♿",
    color: "#3F6E8C",
    categoryId: "transportation",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 3,
    isDefault: true
  },
  {
    id: "phrase-bag-help",
    text: "Can you help me with my bag?",
    label: "Bag help",
    emoji: "🧳",
    color: "#B08443",
    categoryId: "transportation",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 4,
    isDefault: true
  },
  {
    id: "phrase-how-are-you",
    text: "How are you?",
    label: "How are you?",
    emoji: "🙂",
    color: "#2F7E6B",
    categoryId: "social",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 0,
    isDefault: true
  },
  {
    id: "phrase-nice-meet",
    text: "Nice to meet you.",
    label: "Nice to meet you",
    emoji: "🤝",
    color: "#2F7E6B",
    categoryId: "social",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 1,
    isDefault: true
  },
  {
    id: "phrase-my-name",
    text: "My name is ...",
    label: "My name",
    emoji: "👤",
    color: "#3F6E8C",
    categoryId: "social",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 2,
    isDefault: true
  },
  {
    id: "phrase-communicate-app",
    text: "I communicate using this app.",
    label: "This app",
    emoji: "📱",
    color: "#7A6485",
    categoryId: "social",
    voiceId: null,
    language: null,
    isPinned: true,
    isQuickAccess: false,
    sortOrder: 3,
    isDefault: true
  },
  {
    id: "phrase-moment",
    text: "Please give me a moment to type.",
    label: "A moment",
    emoji: "⌨️",
    color: "#B08443",
    categoryId: "social",
    voiceId: null,
    language: null,
    isPinned: false,
    isQuickAccess: false,
    sortOrder: 4,
    isDefault: true
  }
];
